# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 3.3'

gem 'rails', '~> 8.0'
gem 'pg', '~> 1.5'
gem 'pgvector', '~> 0.3'
gem 'puma', '~> 6.4'
gem 'solid_queue', '~> 1.1'
gem 'jwt', '~> 2.9'
gem 'rack-attack', '~> 6.7'
gem 'lograge', '~> 0.14'
gem 'bootsnap', '~> 1.18', require: false

group :development, :test do
  gem 'rspec-rails', '~> 7.0'
  gem 'factory_bot_rails', '~> 6.4'
  gem 'brakeman', '~> 6.2', require: false
  gem 'bundler-audit', '~> 0.9', require: false
end

group :test do
  gem 'shoulda-matchers', '~> 6.2'
  gem 'simplecov', '~> 0.22', require: false
  gem 'database_cleaner-active_record', '~> 2.2'
end

group :development do
  gem 'rubocop-rails-omakase', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rspec', require: false
end
