default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres://sovereign:sovereign@localhost:5432/sovereign_library_development") %>

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL", "postgres://sovereign:sovereign@localhost:5432/sovereign_library_test") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
