AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 7

Metrics/ParameterLists:
  Max: 5

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/Documentation:
  Enabled: false
