AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

plugins:
  - rubocop-rails
  - rubocop-rspec

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/**/*'

Metrics/CyclomaticComplexity:
  Max: 6

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19
