source "https://rubygems.org"

gem "rails", "~> 8.0"
gem "bcrypt", "~> 3.1"
gem "pg", "~> 1.5"
gem "puma", ">= 5"
gem "solid_queue", "~> 1.1"
gem "solid_cache", "~> 1.0"
gem "propshaft"
gem "turbo-rails"
gem "stimulus-rails"
gem "cssbundling-rails"
gem "importmap-rails"
gem "aws-sdk-s3", require: false
gem "pgvector", "~> 0.3"
# git operations use the CLI (git is installed in the container)
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails", "~> 6.4"
end

group :test do
  gem "shoulda-matchers", "~> 6.0"
  gem "capybara"
  gem "selenium-webdriver"
end

group :development do
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
end
