default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "postgres") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "unpossible") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "unpossible") %>

development:
  <<: *default
  database: unpossible_development

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "unpossible_test") %>

production:
  <<: *default
  database: unpossible_production
